"""empty message

Revision ID: d7d7e50045db
Revises: 5295a61dd05d
Create Date: 2025-04-07 00:11:47.133672

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = 'd7d7e50045db'
down_revision = '5295a61dd05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_ocorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.SmallInteger(), nullable=True),
    sa.Column('descricao', sa.String(length=125), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=31983, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['tb_categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_ocorrencias', schema=None) as batch_op:
        batch_op.create_index('idx_tb_ocorrencias_geom', ['geom'], unique=False, postgresql_using='gist')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_ocorrencias', schema=None) as batch_op:
        batch_op.drop_index('idx_tb_ocorrencias_geom', postgresql_using='gist')

    op.drop_table('tb_ocorrencias')
    op.drop_table('tb_categoria')
    # ### end Alembic commands ###
