"""empty message

Revision ID: 6cfeba3285e0
Revises: d7d7e50045db
Create Date: 2025-04-07 00:20:06.771671

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6cfeba3285e0'
down_revision = 'd7d7e50045db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_categoria', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    with op.batch_alter_table('tb_ocorrencias', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
        batch_op.alter_column('data_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_ocorrencias', schema=None) as batch_op:
        batch_op.alter_column('data_registro',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('categoria_id',
               existing_type=sa.SMALLINT(),
               nullable=True)

    with op.batch_alter_table('tb_categoria', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###
