"""empty message

Revision ID: f8bd3bf8e2d6
Revises: b1c52d80b46e
Create Date: 2025-04-12 14:31:00.252683

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'f8bd3bf8e2d6'
down_revision = 'b1c52d80b46e'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.SmallInteger(), nullable=False),
    sa.Column('descricao', sa.String(length=125), nullable=True),
    sa.Column('data_registro', sa.DateTime(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('limites_df',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='limites_df_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('ocorrencias', schema=None) as batch_op:
        batch_op.drop_index('idx_ocorrencias_geom', postgresql_using='gist')

    op.drop_table('ocorrencias')
    op.drop_table('categoria')
    # ### end Alembic commands ###
